/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedIngredientsRouteImport } from './routes/_authed/ingredients'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedBooksRouteImport } from './routes/_authed/books'
import { Route as AuthedShoppingIndexRouteImport } from './routes/_authed/shopping/index'
import { Route as AuthedRecipesIndexRouteImport } from './routes/_authed/recipes/index'
import { Route as AuthedIngredientsIndexRouteImport } from './routes/_authed/ingredients/index'
import { Route as AuthedRecipesNewRouteImport } from './routes/_authed/recipes/new'
import { Route as AuthedRecipesImportRouteImport } from './routes/_authed/recipes/import'
import { Route as AuthedIngredientsCategoriesRouteImport } from './routes/_authed/ingredients/categories'
import { Route as AuthedBooksLibraryRouteImport } from './routes/_authed/books/_library'
import { Route as AuthedRecipesRecipeIdIndexRouteImport } from './routes/_authed/recipes/$recipeId.index'
import { Route as AuthedBooksLibraryIndexRouteImport } from './routes/_authed/books/_library/index'
import { Route as AuthedRecipesRecipeIdEditRouteImport } from './routes/_authed/recipes/$recipeId.edit'
import { Route as AuthedBooksLibraryNewRouteImport } from './routes/_authed/books/_library/new'
import { Route as AuthedBooksLibraryBookIdRouteImport } from './routes/_authed/books/_library/$bookId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIngredientsRoute = AuthedIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBooksRoute = AuthedBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedShoppingIndexRoute = AuthedShoppingIndexRouteImport.update({
  id: '/shopping/',
  path: '/shopping/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipesIndexRoute = AuthedRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIngredientsIndexRoute = AuthedIngredientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedIngredientsRoute,
} as any)
const AuthedRecipesNewRoute = AuthedRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipesImportRoute = AuthedRecipesImportRouteImport.update({
  id: '/recipes/import',
  path: '/recipes/import',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIngredientsCategoriesRoute =
  AuthedIngredientsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthedIngredientsRoute,
  } as any)
const AuthedBooksLibraryRoute = AuthedBooksLibraryRouteImport.update({
  id: '/_library',
  getParentRoute: () => AuthedBooksRoute,
} as any)
const AuthedRecipesRecipeIdIndexRoute =
  AuthedRecipesRecipeIdIndexRouteImport.update({
    id: '/recipes/$recipeId/',
    path: '/recipes/$recipeId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedBooksLibraryIndexRoute = AuthedBooksLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedBooksLibraryRoute,
} as any)
const AuthedRecipesRecipeIdEditRoute =
  AuthedRecipesRecipeIdEditRouteImport.update({
    id: '/recipes/$recipeId/edit',
    path: '/recipes/$recipeId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedBooksLibraryNewRoute = AuthedBooksLibraryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedBooksLibraryRoute,
} as any)
const AuthedBooksLibraryBookIdRoute =
  AuthedBooksLibraryBookIdRouteImport.update({
    id: '/$bookId',
    path: '/$bookId',
    getParentRoute: () => AuthedBooksLibraryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof AuthedBooksLibraryRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/ingredients': typeof AuthedIngredientsRouteWithChildren
  '/ingredients/categories': typeof AuthedIngredientsCategoriesRoute
  '/recipes/import': typeof AuthedRecipesImportRoute
  '/recipes/new': typeof AuthedRecipesNewRoute
  '/ingredients/': typeof AuthedIngredientsIndexRoute
  '/recipes': typeof AuthedRecipesIndexRoute
  '/shopping': typeof AuthedShoppingIndexRoute
  '/books/$bookId': typeof AuthedBooksLibraryBookIdRoute
  '/books/new': typeof AuthedBooksLibraryNewRoute
  '/recipes/$recipeId/edit': typeof AuthedRecipesRecipeIdEditRoute
  '/books/': typeof AuthedBooksLibraryIndexRoute
  '/recipes/$recipeId': typeof AuthedRecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof AuthedBooksLibraryIndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/ingredients/categories': typeof AuthedIngredientsCategoriesRoute
  '/recipes/import': typeof AuthedRecipesImportRoute
  '/recipes/new': typeof AuthedRecipesNewRoute
  '/ingredients': typeof AuthedIngredientsIndexRoute
  '/recipes': typeof AuthedRecipesIndexRoute
  '/shopping': typeof AuthedShoppingIndexRoute
  '/books/$bookId': typeof AuthedBooksLibraryBookIdRoute
  '/books/new': typeof AuthedBooksLibraryNewRoute
  '/recipes/$recipeId/edit': typeof AuthedRecipesRecipeIdEditRoute
  '/recipes/$recipeId': typeof AuthedRecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/books': typeof AuthedBooksRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/ingredients': typeof AuthedIngredientsRouteWithChildren
  '/_authed/books/_library': typeof AuthedBooksLibraryRouteWithChildren
  '/_authed/ingredients/categories': typeof AuthedIngredientsCategoriesRoute
  '/_authed/recipes/import': typeof AuthedRecipesImportRoute
  '/_authed/recipes/new': typeof AuthedRecipesNewRoute
  '/_authed/ingredients/': typeof AuthedIngredientsIndexRoute
  '/_authed/recipes/': typeof AuthedRecipesIndexRoute
  '/_authed/shopping/': typeof AuthedShoppingIndexRoute
  '/_authed/books/_library/$bookId': typeof AuthedBooksLibraryBookIdRoute
  '/_authed/books/_library/new': typeof AuthedBooksLibraryNewRoute
  '/_authed/recipes/$recipeId/edit': typeof AuthedRecipesRecipeIdEditRoute
  '/_authed/books/_library/': typeof AuthedBooksLibraryIndexRoute
  '/_authed/recipes/$recipeId/': typeof AuthedRecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/dashboard'
    | '/ingredients'
    | '/ingredients/categories'
    | '/recipes/import'
    | '/recipes/new'
    | '/ingredients/'
    | '/recipes'
    | '/shopping'
    | '/books/$bookId'
    | '/books/new'
    | '/recipes/$recipeId/edit'
    | '/books/'
    | '/recipes/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/dashboard'
    | '/ingredients/categories'
    | '/recipes/import'
    | '/recipes/new'
    | '/ingredients'
    | '/recipes'
    | '/shopping'
    | '/books/$bookId'
    | '/books/new'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/books'
    | '/_authed/dashboard'
    | '/_authed/ingredients'
    | '/_authed/books/_library'
    | '/_authed/ingredients/categories'
    | '/_authed/recipes/import'
    | '/_authed/recipes/new'
    | '/_authed/ingredients/'
    | '/_authed/recipes/'
    | '/_authed/shopping/'
    | '/_authed/books/_library/$bookId'
    | '/_authed/books/_library/new'
    | '/_authed/recipes/$recipeId/edit'
    | '/_authed/books/_library/'
    | '/_authed/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/ingredients': {
      id: '/_authed/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof AuthedIngredientsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/books': {
      id: '/_authed/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AuthedBooksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/shopping/': {
      id: '/_authed/shopping/'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AuthedShoppingIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipes/': {
      id: '/_authed/recipes/'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthedRecipesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ingredients/': {
      id: '/_authed/ingredients/'
      path: '/'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof AuthedIngredientsIndexRouteImport
      parentRoute: typeof AuthedIngredientsRoute
    }
    '/_authed/recipes/new': {
      id: '/_authed/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AuthedRecipesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipes/import': {
      id: '/_authed/recipes/import'
      path: '/recipes/import'
      fullPath: '/recipes/import'
      preLoaderRoute: typeof AuthedRecipesImportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ingredients/categories': {
      id: '/_authed/ingredients/categories'
      path: '/categories'
      fullPath: '/ingredients/categories'
      preLoaderRoute: typeof AuthedIngredientsCategoriesRouteImport
      parentRoute: typeof AuthedIngredientsRoute
    }
    '/_authed/books/_library': {
      id: '/_authed/books/_library'
      path: ''
      fullPath: '/books'
      preLoaderRoute: typeof AuthedBooksLibraryRouteImport
      parentRoute: typeof AuthedBooksRoute
    }
    '/_authed/recipes/$recipeId/': {
      id: '/_authed/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof AuthedRecipesRecipeIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/books/_library/': {
      id: '/_authed/books/_library/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof AuthedBooksLibraryIndexRouteImport
      parentRoute: typeof AuthedBooksLibraryRoute
    }
    '/_authed/recipes/$recipeId/edit': {
      id: '/_authed/recipes/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof AuthedRecipesRecipeIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/books/_library/new': {
      id: '/_authed/books/_library/new'
      path: '/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof AuthedBooksLibraryNewRouteImport
      parentRoute: typeof AuthedBooksLibraryRoute
    }
    '/_authed/books/_library/$bookId': {
      id: '/_authed/books/_library/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AuthedBooksLibraryBookIdRouteImport
      parentRoute: typeof AuthedBooksLibraryRoute
    }
  }
}

interface AuthedBooksLibraryRouteChildren {
  AuthedBooksLibraryBookIdRoute: typeof AuthedBooksLibraryBookIdRoute
  AuthedBooksLibraryNewRoute: typeof AuthedBooksLibraryNewRoute
  AuthedBooksLibraryIndexRoute: typeof AuthedBooksLibraryIndexRoute
}

const AuthedBooksLibraryRouteChildren: AuthedBooksLibraryRouteChildren = {
  AuthedBooksLibraryBookIdRoute: AuthedBooksLibraryBookIdRoute,
  AuthedBooksLibraryNewRoute: AuthedBooksLibraryNewRoute,
  AuthedBooksLibraryIndexRoute: AuthedBooksLibraryIndexRoute,
}

const AuthedBooksLibraryRouteWithChildren =
  AuthedBooksLibraryRoute._addFileChildren(AuthedBooksLibraryRouteChildren)

interface AuthedBooksRouteChildren {
  AuthedBooksLibraryRoute: typeof AuthedBooksLibraryRouteWithChildren
}

const AuthedBooksRouteChildren: AuthedBooksRouteChildren = {
  AuthedBooksLibraryRoute: AuthedBooksLibraryRouteWithChildren,
}

const AuthedBooksRouteWithChildren = AuthedBooksRoute._addFileChildren(
  AuthedBooksRouteChildren,
)

interface AuthedIngredientsRouteChildren {
  AuthedIngredientsCategoriesRoute: typeof AuthedIngredientsCategoriesRoute
  AuthedIngredientsIndexRoute: typeof AuthedIngredientsIndexRoute
}

const AuthedIngredientsRouteChildren: AuthedIngredientsRouteChildren = {
  AuthedIngredientsCategoriesRoute: AuthedIngredientsCategoriesRoute,
  AuthedIngredientsIndexRoute: AuthedIngredientsIndexRoute,
}

const AuthedIngredientsRouteWithChildren =
  AuthedIngredientsRoute._addFileChildren(AuthedIngredientsRouteChildren)

interface AuthedRouteChildren {
  AuthedBooksRoute: typeof AuthedBooksRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedIngredientsRoute: typeof AuthedIngredientsRouteWithChildren
  AuthedRecipesImportRoute: typeof AuthedRecipesImportRoute
  AuthedRecipesNewRoute: typeof AuthedRecipesNewRoute
  AuthedRecipesIndexRoute: typeof AuthedRecipesIndexRoute
  AuthedShoppingIndexRoute: typeof AuthedShoppingIndexRoute
  AuthedRecipesRecipeIdEditRoute: typeof AuthedRecipesRecipeIdEditRoute
  AuthedRecipesRecipeIdIndexRoute: typeof AuthedRecipesRecipeIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBooksRoute: AuthedBooksRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedIngredientsRoute: AuthedIngredientsRouteWithChildren,
  AuthedRecipesImportRoute: AuthedRecipesImportRoute,
  AuthedRecipesNewRoute: AuthedRecipesNewRoute,
  AuthedRecipesIndexRoute: AuthedRecipesIndexRoute,
  AuthedShoppingIndexRoute: AuthedShoppingIndexRoute,
  AuthedRecipesRecipeIdEditRoute: AuthedRecipesRecipeIdEditRoute,
  AuthedRecipesRecipeIdIndexRoute: AuthedRecipesRecipeIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
